#!/bin/bash
# Use this command to create a builder for named platforms,
# build the Dockerfile on those platforms, then clean up the builder.

BUILDER=$( basename "$PWD" )
PLATFORMS="linux/arm64,linux/amd64"
TAG="rockitthill/rails6"

# Assign a tag version if an argument is passed in
if [[ $# -eq 1 ]] ; then
  TAG="$TAG:$1"
fi

echo ""
echo "🚀 Building for $TAG started."
echo ""
echo "🚀 Creating buildx builder \"$BUILDER\"..."
docker buildx create --use --name $BUILDER --platform $PLATFORMS
echo ""
echo "🚀 Building multi-platform images..."
docker buildx build --push . --platform $PLATFORMS --tag $TAG
echo ""
echo "🚀 Done! Removing builder..."
docker buildx rm $BUILDER